version: "3"
services:
  memo-client:
    build:
      context: client/
      dockerfile: client-dockerfile
    ports:
      - 3000:3000
    container_name: memo-client
  memo-server:
    build:
      context: server/
      dockerfile: server-dockerfile
    ports:
      - 5000:5000
    container_name: memo-server
    depends_on:
    - memo-db
  memo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    container_name: memo-db
networks:
  memo-app:
    driver: bridge
volumes:
  mongodata:
    driver: local