apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels |  nindent 4}}
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      {{- toYaml .Values.labels |  nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.labels |  nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        imagePullPolicy: Always
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        resources:
         {{- toYaml .Values.resources | nindent 12 }}
        ports:
         {{- toYaml .Values.ports | nindent 12 }}
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 12 }}
      {{- end }}