Vagrant.configure("2") do |jenkins|
    jenkins.vm.define "jenkins" do |jenkins|
        jenkins.vm.box =  'ubuntu/focal64'
        jenkins.vm.network "private_network", ip: "10.10.10.20"
        jenkins.vm.hostname = "jenkins"
        jenkins.vm.provision "ansible" do |ansible|
            ansible.playbook = "../../ansible-playbook/jenkins.yaml"
        end
            jenkins.vm.provider "virtualbox" do |v|
                v.memory = 2064
                v.cpus = 2
         end
    end
end