Vagrant.configure("2") do |master|
    master.vm.define "master" do |master|
        master.vm.box =  'ubuntu/focal64'
        master.vm.network "private_network", ip: "10.10.10.20"
        master.vm.hostname = "master"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "/home/yusuf/homelab/docker/project_mern_memories/ansible/jenkins.yaml"
        end
            master.vm.provider "virtualbox" do |v|
                v.memory = 2064
                v.cpus = 2
         end
    end
end