apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    {{- toYaml .Values.labels |  nindent 6 }}
  ports:
    {{- toYaml .Values.servicePort | nindent 6 }}
  type: {{ .Values.serviceType }}